-- AlterTable
ALTER TABLE "Objective" ADD COLUMN     "current" DOUBLE PRECISION NOT NULL DEFAULT 0,
ADD COLUMN     "target" DOUBLE PRECISION NOT NULL DEFAULT 100;

-- AlterTable
ALTER TABLE "ObjectiveAction" ADD COLUMN     "progress" DOUBLE PRECISION NOT NULL DEFAULT 0;
